name: Build and Push Containers to Azure

on:
  push:
    branches: [ main ]
    paths:
      - 'SIMS/**'
      - 'SIMSAPI/**'
      - '.github/workflows/build-push-containers.yml'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push SIMS container
        uses: docker/build-push-action@v5
        with:
          context: ./SIMS
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/sims:${{ github.sha }}, ${{ secrets.ACR_LOGIN_SERVER }}/sims:latest
          cache-from: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/sims:buildcache
          cache-to: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/sims:buildcache,mode=max
      
      - name: Build and push SIMSAPI container
        uses: docker/build-push-action@v5
        with:
          context: ./SIMSAPI
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/simsapi:${{ github.sha }}, ${{ secrets.ACR_LOGIN_SERVER }}/simsapi:latest
          cache-from: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/simsapi:buildcache
          cache-to: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/simsapi:buildcache,mode=max

      - name: Stop SIMSAPI container
        run: az container stop --resource-group RG_OS_CCS --name simsapi

      - name: Stop SIMS container
        run: az container stop --resource-group RG_OS_CCS --name sims

      - name: Start SIMSAPI container
        run: az container start --resource-group RG_OS_CCS --name simsapi

      - name: Start SIMS container
        run: az container start --resource-group RG_OS_CCS --name sims
